export const HOMEPAGE = '/'
export const STATES = '/states'
export const COUNTIES = '/states/:id/counties'
export const STATES_ENDPOINT = 'http://localhost:3000/api/v1/states'
export const STATE_COUNTIES_ENDPOINT = 'http://localhost:3000/api/v1/states/:id/counties'
